### ISSUE TITLE
Truncation

### ISSUE THREAD

**Issue by khttknoob** [flairNLP/flair#1736]
**Describe the bug**
Getting this warining
Truncation was not explicitely activated but `max_length` is provided a specific value, please use `truncation=True` to explicitely truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.

**To Reproduce**
I ran the transformers model a month ago didn't got anything but today getting this warning

**Environment (please complete the following information):**
 - OS [Using Google Colab]

**Comment by alanakbik** [comment]
Did you update to transformers 3.0 in the meantime?

**Comment by alanakbik** [comment]
Also, could you provide a code snippet to reproduce?

**Comment by alanakbik** [comment]
This is now fixed in flair 0.5.1!

**Comment by martjushev** [comment]
I'm on flair 0.5.1 and transformers 3.0.2 and I still see this warning when using SentenceTransformerDocumentEmbeddings
