### ISSUE TITLE
URL endpoints within flair to fetch model/files not working

### ISSUE THREAD

**Issue by thekeshavgoel** [flairNLP/flair#2661]
**Describe the bug**
Failing to execute `TARSClassifier.load(model="tars-base")` when running first time, i.e. the `tars-base-v8.pt` file isn't already downloaded and cached locally.
When trying to load the model for first time, getting following error:
```
 raise IOError(
OSError: HEAD request failed for url https://nlp.informatik.hu-berlin.de/resources/models/tars-base/tars-base-v8.pt with status code 503.
```

**To Reproduce**
Clear the `~/.flair/model/tars-base-v8.pt`, and try executing `TARSClassifier.load(model="tars-base")`

**Expected behavior**
The file should have downloaded and model loaded successfully.

**Environment (please complete the following information):**
 - OS : Linux and OSX
 - Version : flair >= 0.10

**Comment by SaraKaminska** [comment]
I have the same issue with loading the Tars NER model (TARSTagger.load('tars-ner'). 
The error message is: OSError: HEAD request failed for url https://nlp.informatik.hu-berlin.de/resources/models/tars-ner/tars-ner.pt with status code 503.

**Comment by thekeshavgoel** [comment]
@alanakbik  - (sorry to tag) - but is this something you/team looking into soon?!

**Comment by alanakbik** [comment]
Oha thanks for reporting this, we'll look into it!

**Comment by gitlost-murali** [comment]
Same issue with WordEmbeddings('en-crawl'), FlairEmbeddings('news-forward'), etc.

**Comment by alanakbik** [comment]
Should be fixed now!

**Comment by RobinMeneust** [comment]
I still have this error for tars-base. https://nlp.informatik.hu-berlin.de/resources/models/tars-base/tars-base-v8.pt seems to be currently unavailable (Error 503).
